# .github/workflows/trigger-repo2.yml
name: Trigger repo2 workflow

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  trigger-repo2:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow in repo2
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"event_type": "triggered_by_repo1","client_payload":{"unit":false,"integration":true}}' \
          https://api.github.com/repos/serhii-vasylkiv/repo2/dispatches
